version: '3.8'

services:

  webserver:

    container_name: webserver
    
    image: nginx:latest
    
    restart: always

    environment:
      TZ: "Asia/Seoul"
    
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/build:/usr/share/front/build
    
    depends_on:
      - webapp_1
      # - webapp_2

    ports:
      - 80:80
    
    networks:
      - noops


  webapp_1:

    container_name: webapp_1

    restart: always

    depends_on:
      - db

    build: 
      context: .
      dockerfile: ./docker/backend.dockerfile

    volumes:
      - ./app.log:/app/app.log

    environment:
      TZ: "Asia/Seoul"


    command: sh -c "cd /app && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"

    networks:
      - noops


  # webapp_2:

  #   container_name: webapp_2

  #   restart: always

  #   build: 
  #     context: .
  #     dockerfile: ./docker/backend.dockerfile

  #   volumes: # 사용자 한테 받은 이미지 저장 필요
  #     - ./raw_image:/app/raw_image

  #   command: sh -c "cd /app && uvicorn main:app --host 0.0.0.0 --port 8001"

  #   networks:
  #     - noops


  db:

    image: postgres:14.0

    container_name: db
  
    restart: always

    env_file:
      - ./config/db/.env

    volumes:
      - data-vol:/var/lib/postgresql/data
      - ./config/db/initdb.d/:/docker-entrypoint-initdb.d/

    networks:
      - noops

    expose:
      - 5432
    
    ports:
      - 5432:5432

networks:
  noops:
    driver: bridge

volumes:
  data-vol:
    driver: local