version: "3"

services:
  postgres-server:
    image: postgres:14.0
    container_name: postgres-server
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - "./init/:/docker-entrypoint-initdb.d/"
  
  # data-info-to-db:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: data-info-to-db
  #   depends_on:
  #     postgres-server:
  #       condition: service_healthy
  #   command: ["postgres-server"]